import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        void: "#09090B",
        surface: "#f9f9ff",
        "border-subtle": "#27272A",
        neon: "#10B981",
        "neon-dim": "#064E3B",
        danger: "#EF4444",
        "tertiary-fixed-dim": "#c3c7cb",
        "on-primary-fixed-variant": "#173bab",
        "secondary-container": "#40c2fd",
        "on-surface-variant": "#444653",
        "tertiary-fixed": "#dfe3e7",
        "on-secondary-fixed-variant": "#004c69",
        "primary-container": "#1e40af",
        "outline-variant": "#c4c5d5",
        "primary-fixed": "#dde1ff",
        "surface-container-highest": "#d8e3fb",
        "surface-container-high": "#dee8ff",
        "surface-tint": "#3755c3",
        tertiary: "#303539",
        secondary: "#00668a",
        "surface-dim": "#cfdaf2",
        "inverse-on-surface": "#ecf1ff",
        "on-tertiary-fixed": "#171c1f",
        "inverse-surface": "#263143",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#7bd0ff",
        "on-primary-fixed": "#001453",
        "error-container": "#ffdad6",
        "on-secondary-container": "#004d6a",
        "surface-variant": "#d8e3fb",
        "on-surface": "#111c2d",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        outline: "#757684",
        "surface-container": "#e7eeff",
        background: "#f9f9ff",
        "on-background": "#111c2d",
        "tertiary-container": "#474c4f",
        "on-tertiary-container": "#b8bcc0",
        "primary-fixed-dim": "#b8c4ff",
        "on-primary-container": "#a8b8ff",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "on-secondary-fixed": "#001e2c",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#43474b",
        primary: "#00288e",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#c4e7ff",
        "on-error-container": "#93000a",
        "inverse-primary": "#b8c4ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        md: "16px",
        base: "4px",
        gutter: "24px",
        xs: "4px",
        "margin-mobile": "16px",
        "3xl": "64px",
        "2xl": "48px",
        "margin-desktop": "40px",
        sm: "8px",
        lg: "24px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["var(--font-plus-jakarta)", "sans-serif"],
        display: ["var(--font-plus-jakarta)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        display: ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
